version: "3.9"
services:

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: bot
    depends_on:
      - redis
    volumes:
      - .:/app
